// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("F2F.ReactiveNavigation.WPF.Sample")]
[assembly: AssemblyProductAttribute("F2F.ReactiveNavigation")]
[assembly: AssemblyDescriptionAttribute("Region-based navigation on top of ReactiveUI and some extra goodies")]
[assembly: AssemblyVersionAttribute("2.0.5")]
[assembly: AssemblyFileVersionAttribute("2.0.5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.5";
    }
}
