// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("F2F.ReactiveNavigation.WPF")]
[assembly: AssemblyProductAttribute("F2F.ReactiveNavigation")]
[assembly: AssemblyDescriptionAttribute("Region-based navigation on top of ReactiveUI and some extra goodies")]
[assembly: AssemblyVersionAttribute("4.0.2")]
[assembly: AssemblyFileVersionAttribute("4.0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "F2F.ReactiveNavigation.WPF";
        internal const System.String AssemblyProduct = "F2F.ReactiveNavigation";
        internal const System.String AssemblyDescription = "Region-based navigation on top of ReactiveUI and some extra goodies";
        internal const System.String AssemblyVersion = "4.0.2";
        internal const System.String AssemblyFileVersion = "4.0.2";
    }
}
